const cfg=window.BIG_ALIEN_CONFIG||{};
const ready=cfg.SUPABASE_URL&&!cfg.SUPABASE_URL.includes('PASTE_')&&cfg.SUPABASE_PUBLISHABLE_KEY&&!cfg.SUPABASE_PUBLISHABLE_KEY.includes('PASTE_');
const sb=ready?window.supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_PUBLISHABLE_KEY):null;
const $=id=>document.getElementById(id); const money=n=>'₦'+Number(n||0).toLocaleString('en-NG',{maximumFractionDigits:0}); const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m])); const img=u=>u||'images/solar-panel.jpg';
function showDenied(){ $('checking').classList.add('hidden'); $('adminApp').classList.add('hidden'); $('denied').classList.remove('hidden'); }
async function check(){if(!sb){return showDenied()} const {data:{session}}=await sb.auth.getSession(); if(!session)return showDenied(); const {data:p}=await sb.from('profiles').select('role').eq('id',session.user.id).single(); if(p?.role!=='admin')return showDenied(); $('checking').classList.add('hidden'); $('adminApp').classList.remove('hidden'); await loadProducts(); await loadOrders();}
async function loadProducts(){const {data,error}=await sb.from('products').select('*').order('created_at',{ascending:false}); if(error){$('adminProducts').innerHTML='<div class="summary">'+esc(error.message)+'</div>';return} const rows=(data||[]).map(p=>`<div class="adminRow"><img src="${esc(img(p.image_url))}" alt=""><div><b>${esc(p.name)}</b><div class="muted">${esc(p.category)}</div></div><div>${money(p.price)}</div><div>${p.stock}</div><div>${p.active?'Live':'Hidden'}</div><div><button class="secondary" data-edit="${p.id}">Edit</button> <button class="danger" data-delete="${p.id}">Delete</button></div></div>`).join(''); $('adminProducts').innerHTML=`<div class="adminTable"><div class="adminRow"><b>Image</b><b>Product</b><b>Price</b><b>Stock</b><b>Status</b><b>Actions</b></div>${rows||'<div class="summary">No products yet.</div>'}</div>`;}
async function loadOrders(){const {data,error}=await sb.from('orders').select('*').order('created_at',{ascending:false}); if(error){$('adminOrders').innerHTML='<div class="summary">'+esc(error.message)+'</div>';return} $('adminOrders').innerHTML=(data||[]).map(o=>`<div class="orderCard"><b>Order ${o.id.slice(0,8)}</b><p>${esc(o.customer_name)} · ${esc(o.customer_phone)} · ${money(o.total)}</p><p>Payment: <span class="status">${esc(o.payment_status)}</span> · Shipment: <span class="status">${esc(o.order_status)}</span></p><p>Tracking: ${esc(o.tracking_number||'Not assigned')}</p><p>Address: ${esc(o.delivery_address)}</p><button class="primary" data-order="${o.id}">Manage Order & Shipment</button></div>`).join('')||'<div class="summary">No orders yet.</div>';}
function openProduct(p){$('productModalTitle').textContent=p?'Edit Product':'Add Product';$('productId').value=p?.id||'';$('productName').value=p?.name||'';$('productCategory').value=p?.category||'Solar';$('productPrice').value=p?.price??'';$('productStock').value=p?.stock??0;$('productDescription').value=p?.description||'';$('productImage').value='';$('imagePreview').innerHTML=p?.image_url?`<img class="preview" src="${esc(p.image_url)}">`:'';$('productMsg').textContent='';$('productModal').classList.remove('hidden');}
async function saveProduct(e){e.preventDefault();let id=$('productId').value,file=$('productImage').files[0],image_url=null;if(file){let ext=(file.name.split('.').pop()||'jpg').toLowerCase(),path=`${crypto.randomUUID()}.${ext}`;let {error}=await sb.storage.from('product-images').upload(path,file,{upsert:false,contentType:file.type});if(error){$('productMsg').textContent=error.message;return}image_url=sb.storage.from('product-images').getPublicUrl(path).data.publicUrl}let payload={name:$('productName').value.trim(),category:$('productCategory').value,price:Number($('productPrice').value),stock:Number($('productStock').value),description:$('productDescription').value.trim()};if(image_url)payload.image_url=image_url;let r=id?await sb.from('products').update(payload).eq('id',id):await sb.from('products').insert(payload);if(r.error){$('productMsg').textContent=r.error.message;return}$('productModal').classList.add('hidden');await loadProducts();}
async function deleteProduct(id){if(!confirm('Delete this product?'))return;const {error}=await sb.from('products').delete().eq('id',id);if(error)alert(error.message);else loadProducts();}
async function manageOrder(id){const {data:o,error}=await sb.from('orders').select('*').eq('id',id).single();if(error)return alert(error.message);const {data:ups}=await sb.from('shipment_updates').select('*').eq('order_id',id).order('created_at',{ascending:false});$('orderModalBody').innerHTML=`<h2>Manage Order ${id.slice(0,8)}</h2><p>${esc(o.customer_name)} · ${esc(o.customer_phone)}</p><p>${esc(o.delivery_address)}</p><label>Payment status<select id="mPay"><option ${o.payment_status==='pending'?'selected':''}>pending</option><option ${o.payment_status==='paid'?'selected':''}>paid</option><option ${o.payment_status==='failed'?'selected':''}>failed</option><option ${o.payment_status==='refunded'?'selected':''}>refunded</option></select></label><label>Shipment status<select id="mStatus">${['processing','confirmed','shipped','out_for_delivery','delivered','cancelled'].map(s=>`<option value="${s}" ${o.order_status===s?'selected':''}>${s}</option>`).join('')}</select></label><label>Tracking number<input id="mTrack" value="${esc(o.tracking_number||'')}"></label><label>Shipment update<textarea id="mMessage" placeholder="e.g. Package has left Abuja sorting centre"></textarea></label><label>Location<input id="mLocation" placeholder="e.g. Abuja"></label><button class="primary" id="saveOrder">Save Update</button><h3>Shipment history</h3>${(ups||[]).map(u=>`<div class="summary">📍 <b>${esc(u.status)}</b> — ${esc(u.message)}<br><span class="muted">${esc(u.location||'')} ${new Date(u.created_at).toLocaleString()}</span></div>`).join('')||'<p class="muted">No shipment updates yet.</p>'}`;$('saveOrder').onclick=async()=>{const {error}=await sb.from('orders').update({payment_status:$('mPay').value,order_status:$('mStatus').value,tracking_number:$('mTrack').value.trim()||null}).eq('id',id);if(error)return alert(error.message);if($('mMessage').value.trim()){const {error:e}=await sb.from('shipment_updates').insert({order_id:id,status:$('mStatus').value,message:$('mMessage').value.trim(),location:$('mLocation').value.trim()||null});if(e)return alert(e.message)}$('orderModal').classList.add('hidden');await loadOrders();alert('Order updated. The customer will see the new shipment status.');};$('orderModal').classList.remove('hidden');}
document.addEventListener('click',async e=>{const t=e.target;if(t.dataset.tab){document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x===t));$('productsTab').classList.toggle('hidden',t.dataset.tab!=='products');$('ordersTab').classList.toggle('hidden',t.dataset.tab!=='orders');}if(t.id==='addProductBtn')openProduct();if(t.dataset.edit){const {data}=await sb.from('products').select('*').eq('id',t.dataset.edit).single();if(data)openProduct(data)}if(t.dataset.delete)deleteProduct(t.dataset.delete);if(t.dataset.order)manageOrder(t.dataset.order);if(t.dataset.close)$(t.dataset.close).classList.add('hidden');});
$('productForm').onsubmit=saveProduct;$('adminLogout').onclick=async()=>{await sb.auth.signOut();location.href='./'};$('backHome').onclick=()=>location.href='./';$('deniedLogin').onclick=()=>location.href='./';
check();
